services:
  drawdb:
    build: .
    container_name: drawdb-integrated
    ports:
      - "3001:3001"
    volumes:
      - ./backend/drawdb.sqlite:/app/backend/drawdb.sqlite
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge
